
-- 1. Clean up existing objects (Careful: this deletes data)
-- DROP TABLE IF EXISTS quiz_responses CASCADE;
-- DROP TABLE IF EXISTS published_quizzes CASCADE;
-- DROP TABLE IF EXISTS blackboard_sessions CASCADE;
-- DROP TABLE IF EXISTS study_sessions CASCADE;
-- DROP TABLE IF EXISTS tasks CASCADE;
-- DROP TABLE IF EXISTS notes CASCADE;
-- DROP TABLE IF EXISTS lectures CASCADE;
-- DROP TABLE IF EXISTS subjects CASCADE;
-- DROP TABLE IF EXISTS profiles CASCADE;
-- DROP TABLE IF EXISTS mind_maps CASCADE;
-- DROP TABLE IF EXISTS presentations CASCADE;
-- DROP TABLE IF EXISTS ai_conversations CASCADE;
-- DROP TABLE IF EXISTS ai_images CASCADE;

-- 2. Create Tables
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  xp INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  color TEXT DEFAULT 'bg-indigo-500',
  progress INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lectures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  subject_id BIGINT REFERENCES subjects ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  type TEXT NOT NULL, -- 'file' or 'link'
  content TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  lecture_id BIGINT REFERENCES lectures ON DELETE SET NULL,
  title TEXT NOT NULL,
  time TEXT,
  duration TEXT,
  day_index INTEGER DEFAULT 0,
  subject_color TEXT DEFAULT 'bg-indigo-500',
  is_exam BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'upcoming', -- 'upcoming', 'completed'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  duration_minutes INTEGER NOT NULL,
  subject TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blackboard_sessions (
  id TEXT PRIMARY KEY DEFAULT extensions.uuid_generate_v4()::text,
  creator_id UUID REFERENCES auth.users ON DELETE SET NULL,
  data JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mind_maps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS published_quizzes (
  id TEXT PRIMARY KEY,
  creator_id UUID REFERENCES auth.users ON DELETE SET NULL,
  settings JSONB NOT NULL,
  questions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id TEXT REFERENCES published_quizzes ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  score INTEGER NOT NULL,
  total_questions INTEGER NOT NULL,
  answers JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS presentations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  slides JSONB NOT NULL,
  lang TEXT DEFAULT 'ar',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_sessions (
  id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  session_id UUID REFERENCES chat_sessions ON DELETE CASCADE,
  role TEXT NOT NULL, -- 'user', 'ai'
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  prompt TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE lectures ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE blackboard_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE mind_maps ENABLE ROW LEVEL SECURITY;
ALTER TABLE published_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE presentations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_images ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Unique names to avoid conflicts)

-- Profiles
CREATE POLICY p_profiles_owner ON profiles FOR ALL USING (auth.uid() = id);

-- Subjects
CREATE POLICY p_subjects_owner ON subjects FOR ALL USING (auth.uid() = user_id);

-- Lectures
CREATE POLICY p_lectures_owner ON lectures FOR ALL USING (auth.uid() = user_id);

-- Tasks
CREATE POLICY p_tasks_owner ON tasks FOR ALL USING (auth.uid() = user_id);

-- Notes
CREATE POLICY p_notes_owner ON notes FOR ALL USING (auth.uid() = user_id);

-- Study Sessions
CREATE POLICY p_study_sessions_owner ON study_sessions FOR ALL USING (auth.uid() = user_id);

-- Blackboard Sessions (Public read/write for collaboration, but creator can delete)
CREATE POLICY p_blackboard_public_access ON blackboard_sessions FOR ALL USING (true);

-- Mind Maps
CREATE POLICY p_mind_maps_owner ON mind_maps FOR ALL USING (auth.uid() = user_id);

-- Published Quizzes (Public read, creator write)
CREATE POLICY p_quizzes_public_read ON published_quizzes FOR SELECT USING (true);
CREATE POLICY p_quizzes_creator_all ON published_quizzes FOR ALL USING (auth.uid() = creator_id);

-- Quiz Responses (Public insert, creator/user read)
CREATE POLICY p_quiz_responses_insert ON quiz_responses FOR INSERT WITH CHECK (true);
CREATE POLICY p_quiz_responses_read ON quiz_responses FOR SELECT USING (auth.uid() = user_id OR auth.uid() IN (SELECT creator_id FROM published_quizzes WHERE id = quiz_id));

-- Presentations
CREATE POLICY p_presentations_owner ON presentations FOR ALL USING (auth.uid() = user_id);

-- AI Conversations
CREATE POLICY p_ai_conversations_owner ON ai_conversations FOR ALL USING (auth.uid() = user_id);

-- AI Images
CREATE POLICY p_ai_images_owner ON ai_images FOR ALL USING (auth.uid() = user_id);

-- 5. Storage Configuration
-- Ensure 'files' bucket exists and has public access
-- (This part usually needs to be done in Supabase UI or via API, but policies can be set here)

-- 6. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_subjects_uid ON subjects(user_id);
CREATE INDEX IF NOT EXISTS idx_lectures_sid ON lectures(subject_id);
CREATE INDEX IF NOT EXISTS idx_tasks_uid ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_uid ON notes(user_id);
CREATE INDEX IF NOT EXISTS idx_study_sessions_uid ON study_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_uid ON ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_sid ON ai_conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_uid ON chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_images_uid ON ai_images(user_id);
